name: orchastrator
description: An app aiming to help coordinate people.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0"
dependencies:
  flutter:
    sdk: flutter
  provider:
  shared_preferences:
  path:
  path_provider:
  collection:
  string_validator:
  smart_stepper:
  mobile_scanner:
  async:
  aes256:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true
